import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { readFileSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { tmpdir } from 'node:os';

const core = require('../lib/core.js');

describe('CLI Core', () => {
  describe('transformContent', () => {
    it('should replace volt- selectors with ui-', () => {
      const input = `selector: 'volt-button'`;
      const output = core.transformContent(input);
      expect(output).toContain("selector: 'ui-button'");
    });

    it('should replace Volt class names with Ui', () => {
      const input = `export class VoltButton {}`;
      const output = core.transformContent(input);
      expect(output).toContain('class UiButton');
    });

    it('should replace voltCamelCase with uiCamelCase', () => {
      const input = `const voltThemeColor = 'blue';`;
      const output = core.transformContent(input);
      expect(output).toContain("const uiThemeColor = 'blue';");
    });

    it('should replace imports from volt to local index', () => {
      const input = `import { VoltButton } from 'volt';`;
      const output = core.transformContent(input);
      expect(output).toContain("from './index'");
    });

    it('should not replace non-selector volt strings', () => {
      const input = `const voltage = 12;`;
      const output = core.transformContent(input);
      expect(output).toContain('voltage');
    });

    it('should handle multiple selectors', () => {
      const input = `selector: 'volt-tabs-list'`;
      const output = core.transformContent(input);
      expect(output).toContain("selector: 'ui-tabs-list'");
    });
  });

  describe('getLocalManifest', () => {
    it('should load the local manifest when available', () => {
      const manifest = core.getLocalManifest();
      expect(manifest).toBeTruthy();
      expect(manifest.version).toBeTruthy();
      expect(manifest.components).toBeTruthy();
      expect(Object.keys(manifest.components).length).toBeGreaterThan(0);
    });

    it('should contain button component', () => {
      const manifest = core.getLocalManifest();
      expect(manifest.components.button).toBeTruthy();
      expect(manifest.components.button.files).toContain('components/button/button.ts');
      expect(manifest.components.button.files).toContain('components/button/index.ts');
    });

    it('should contain tabs component', () => {
      const manifest = core.getLocalManifest();
      expect(manifest.components.tabs).toBeTruthy();
      expect(manifest.components.tabs.files).toContain('components/tabs/index.ts');
    });
  });

  describe('initProject', () => {
    let testDir;

    beforeEach(() => {
      testDir = join(tmpdir(), `volt-test-${Date.now()}`);
    });

    afterEach(() => {
      if (existsSync(testDir)) {
        rmSync(testDir, { recursive: true, force: true });
      }
    });

    it('should create the target directory', () => {
      core.initProject(testDir);
      expect(existsSync(testDir)).toBe(true);
    });

    it('should create an index.ts with the expected content', () => {
      core.initProject(testDir);
      const indexPath = join(testDir, 'index.ts');
      expect(existsSync(indexPath)).toBe(true);
      const content = readFileSync(indexPath, 'utf-8');
      expect(content).toContain('UI Components');
      expect(content).toContain('Generated by volt CLI');
    });
  });

  describe('copyComponent', () => {
    let testDir;
    const manifest = core.getLocalManifest();

    beforeEach(() => {
      testDir = join(tmpdir(), `volt-copy-${Date.now()}`);
    });

    afterEach(() => {
      if (existsSync(testDir)) {
        rmSync(testDir, { recursive: true, force: true });
      }
    });

    it('should copy and transform button component', async () => {
      const result = await core.copyComponent('button', testDir, manifest);
      expect(result.componentName).toBe('button');
      expect(result.className).toBe('UiButton');

      const buttonDir = join(testDir, 'button');
      expect(existsSync(buttonDir)).toBe(true);
      expect(existsSync(join(buttonDir, 'button.ts'))).toBe(true);
      expect(existsSync(join(buttonDir, 'index.ts'))).toBe(true);

      const content = readFileSync(join(buttonDir, 'button.ts'), 'utf-8');
      expect(content).toContain("selector: 'ui-button'");
      expect(content).toContain('class UiButton');
      expect(content).not.toContain('class VoltButton');
    });

    it('should copy and transform card component using cache', async () => {
      const cardUrl = `${manifest.baseUrl}/components/card/card.ts`;
      const indexUrl = `${manifest.baseUrl}/components/card/index.ts`;
      core.setCachedFile(
        cardUrl,
        "export const card = 'test';\nexport class VoltCard {}\nselector: 'volt-card'"
      );
      core.setCachedFile(indexUrl, "export * from './card';\n");

      const result = await core.copyComponent('card', testDir, manifest);
      expect(result.componentName).toBe('card');
      expect(result.className).toBe('UiCard');

      const cardDir = join(testDir, 'card');
      const files = readdirSync(cardDir);
      expect(files.length).toBeGreaterThanOrEqual(1);

      const content = readFileSync(join(cardDir, 'card.ts'), 'utf-8');
      expect(content).toContain('class UiCard');
      expect(content).toContain("selector: 'ui-card'");
    });

    it('should throw for unknown component', async () => {
      await expect(core.copyComponent('nonexistent', testDir, manifest)).rejects.toThrow(
        'Component "nonexistent" not found.'
      );
    });
  });

  describe('cache', () => {
    it('should store and retrieve cached files', () => {
      const testUrl = 'https://example.com/test-file.ts';
      const testContent = 'export const foo = 1;';
      core.setCachedFile(testUrl, testContent);
      const retrieved = core.getCachedFile(testUrl);
      expect(retrieved).toBe(testContent);
    });

    it('should return null for uncached files', () => {
      const retrieved = core.getCachedFile('https://example.com/uncached.ts');
      expect(retrieved).toBeNull();
    });
  });
});
