import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { readFileSync, existsSync, rmSync, readdirSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { tmpdir } from 'node:os';
import { execSync } from 'node:child_process';

const core = require('../lib/core.js');

describe('CLI Core', () => {
  describe('transformContent', () => {
    it('should replace volt- selectors with ui-', () => {
      const input = `selector: 'volt-button'`;
      const output = core.transformContent(input);
      expect(output).toContain("selector: 'ui-button'");
    });

    it('should replace Volt class names with Ui', () => {
      const input = `export class VoltButton {}`;
      const output = core.transformContent(input);
      expect(output).toContain('class UiButton');
    });

    it('should replace voltCamelCase with uiCamelCase', () => {
      const input = `const voltThemeColor = 'blue';`;
      const output = core.transformContent(input);
      expect(output).toContain("const uiThemeColor = 'blue';");
    });

    it('should replace imports from volt to local index', () => {
      const input = `import { VoltButton } from 'volt';`;
      const output = core.transformContent(input);
      expect(output).toContain("from './index'");
    });

    it('should not replace non-selector volt strings', () => {
      const input = `const voltage = 12;`;
      const output = core.transformContent(input);
      expect(output).toContain('voltage');
    });

    it('should handle multiple selectors', () => {
      const input = `selector: 'volt-tabs-list'`;
      const output = core.transformContent(input);
      expect(output).toContain("selector: 'ui-tabs-list'");
    });
  });

  describe('getLocalManifest', () => {
    it('should load the local manifest when available', () => {
      const manifest = core.getLocalManifest();
      expect(manifest).toBeTruthy();
      expect(manifest.version).toBeTruthy();
      expect(manifest.components).toBeTruthy();
      expect(Object.keys(manifest.components).length).toBeGreaterThan(0);
    });

    it('should contain button component', () => {
      const manifest = core.getLocalManifest();
      expect(manifest.components.button).toBeTruthy();
      expect(manifest.components.button.files).toContain('components/button/button.ts');
      expect(manifest.components.button.files).toContain('components/button/index.ts');
    });

    it('should contain tabs component', () => {
      const manifest = core.getLocalManifest();
      expect(manifest.components.tabs).toBeTruthy();
      expect(manifest.components.tabs.files).toContain('components/tabs/index.ts');
    });

    it('should not contain a network baseUrl', () => {
      const manifest = core.getLocalManifest();
      expect(manifest.baseUrl).toBeUndefined();
    });
  });

  describe('manifest dependency mapping', () => {
    it('should reflect inter-component dependencies detected from source imports', () => {
      const manifest = core.getLocalManifest();
      // sidebar imports tooltip from the components folder
      expect(manifest.components.sidebar.dependencies).toContain('tooltip');
    });
  });

  describe('initProject', () => {
    let testDir;

    beforeEach(() => {
      testDir = join(tmpdir(), `volt-test-${Date.now()}`);
    });

    afterEach(() => {
      if (existsSync(testDir)) {
        rmSync(testDir, { recursive: true, force: true });
      }
    });

    it('should create the target directory', () => {
      core.initProject(testDir);
      expect(existsSync(testDir)).toBe(true);
    });

    it('should create an index.ts with the expected content', () => {
      core.initProject(testDir);
      const indexPath = join(testDir, 'index.ts');
      expect(existsSync(indexPath)).toBe(true);
      const content = readFileSync(indexPath, 'utf-8');
      expect(content).toContain('UI Components');
      expect(content).toContain('Generated by volt CLI');
    });
  });

  describe('copyComponent', () => {
    let testDir;
    const manifest = core.getLocalManifest();

    beforeEach(() => {
      testDir = join(tmpdir(), `volt-copy-${Date.now()}`);
    });

    afterEach(() => {
      if (existsSync(testDir)) {
        rmSync(testDir, { recursive: true, force: true });
      }
    });

    it('should copy and transform button component', async () => {
      const result = await core.copyComponent('button', testDir, manifest);
      expect(result.componentName).toBe('button');
      expect(result.className).toBe('UiButton');

      const buttonDir = join(testDir, 'button');
      expect(existsSync(buttonDir)).toBe(true);
      expect(existsSync(join(buttonDir, 'button.ts'))).toBe(true);
      expect(existsSync(join(buttonDir, 'index.ts'))).toBe(true);

      const content = readFileSync(join(buttonDir, 'button.ts'), 'utf-8');
      expect(content).toContain("selector: 'ui-button'");
      expect(content).toContain('class UiButton');
      expect(content).not.toContain('class VoltButton');
    });

    it('should copy and transform card component from local source', async () => {
      const result = await core.copyComponent('card', testDir, manifest);
      expect(result.componentName).toBe('card');
      expect(result.className).toBe('UiCard');

      const cardDir = join(testDir, 'card');
      const files = readdirSync(cardDir);
      expect(files.length).toBeGreaterThanOrEqual(1);

      const content = readFileSync(join(cardDir, 'card.ts'), 'utf-8');
      expect(content).toContain('class UiCard');
      expect(content).toContain("selector: 'ui-card'");
    });

    it('should copy transitive dependencies declared in the manifest', async () => {
      const result = await core.copyComponent('sidebar', testDir, manifest);
      expect(result.dependencies).toContain('tooltip');

      const tooltipDir = join(testDir, 'tooltip');
      expect(existsSync(tooltipDir)).toBe(true);
    });

    it('should throw for unknown component', async () => {
      try {
        await core.copyComponent('nonexistent', testDir, manifest);
        expect.unreachable('Expected copyComponent to throw');
      } catch (err) {
        expect(err.message).toContain('Component "nonexistent" not found');
      }
    });
  });

  describe('CLI integration', () => {
    const repoRoot = resolve(__dirname, '../..');
    const cliPath = join(repoRoot, 'cli/bin/volt');
    let testDir;

    beforeEach(() => {
      testDir = join(tmpdir(), `volt-cli-integration-${Date.now()}`);
    });

    afterEach(() => {
      if (existsSync(testDir)) {
        rmSync(testDir, { recursive: true, force: true });
      }
    });

    it('should init and add a component via the CLI binary', () => {
      execSync(`node ${cliPath} init ${testDir}`, { cwd: repoRoot, stdio: 'pipe' });
      expect(existsSync(join(testDir, 'index.ts'))).toBe(true);

      execSync(`node ${cliPath} add button ${testDir}`, { cwd: repoRoot, stdio: 'pipe' });
      expect(existsSync(join(testDir, 'button', 'button.ts'))).toBe(true);

      const indexContent = readFileSync(join(testDir, 'index.ts'), 'utf-8');
      expect(indexContent).toContain("export * from './button';");

      const buttonContent = readFileSync(join(testDir, 'button', 'button.ts'), 'utf-8');
      expect(buttonContent).toContain("selector: 'ui-button'");
      expect(buttonContent).toContain('class UiButton');
    });
  });
});
