// Generated by scripts/generate-api-reference.mjs — do not hand-edit.
// Re-run `node scripts/generate-api-reference.mjs` after changing a
// component's inputs/outputs/variants, then re-check this diff into git
// (this file is committed, not regenerated on every build).

export interface ApiInputInfo {
  name: string;
  type: string;
  default?: string;
  required?: boolean;
  transform?: string;
}

export interface ApiOutputInfo {
  name: string;
  type: string;
}

export interface ApiDirectiveInfo {
  className: string;
  selector: string | null;
  inputs: ApiInputInfo[];
  outputs: ApiOutputInfo[];
}

export interface ApiVariantGroup {
  name: string;
  options: string[];
  default?: string;
}

export interface ComponentApi {
  directives: ApiDirectiveInfo[];
  variants?: ApiVariantGroup[];
}

export const ACCORDION_API: ComponentApi = {
  directives: [
    {
      className: 'VoltAccordionItem',
      selector: 'volt-accordion-item',
      inputs: [{ name: 'value', type: 'string', required: true }],
      outputs: [],
    },
    {
      className: 'VoltAccordion',
      selector: 'volt-accordion',
      inputs: [
        { name: 'type', type: 'NgpAccordionType', default: "'single'" },
        { name: 'collapsible', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'value', type: 'string | string[] | null', default: 'null' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'orientation', type: "'horizontal' | 'vertical'", default: "'vertical'" },
      ],
      outputs: [{ name: 'valueChange', type: 'string | string[] | null' }],
    },
  ],
  variants: undefined,
};

export const AUTOFILL_API: ComponentApi = {
  directives: [
    {
      className: 'VoltAutofill',
      selector: '[voltAutofill]',
      inputs: [],
      outputs: [{ name: 'autofillChange', type: 'unknown' }],
    },
  ],
  variants: undefined,
};

export const AVATAR_API: ComponentApi = {
  directives: [
    {
      className: 'VoltAvatarFallback',
      selector: 'volt-avatar-fallback',
      inputs: [{ name: 'delay', type: 'number', default: '0' }],
      outputs: [],
    },
  ],
  variants: undefined,
};

export const BADGE_API: ComponentApi = {
  directives: [
    {
      className: 'VoltBadge',
      selector: 'volt-badge',
      inputs: [{ name: 'variant', type: "BadgeVariants['variant']", default: "'solid'" }],
      outputs: [],
    },
  ],
  variants: [
    {
      name: 'variant',
      options: ['solid', 'secondary', 'outline', 'destructive'],
      default: 'solid',
    },
  ],
};

export const BREADCRUMBS_API: ComponentApi = {
  directives: [
    {
      className: 'VoltBreadcrumbLink',
      selector: 'volt-breadcrumb-link',
      inputs: [{ name: 'href', type: 'string', default: "'#'" }],
      outputs: [],
    },
  ],
  variants: undefined,
};

export const BUTTON_API: ComponentApi = {
  directives: [
    {
      className: 'VoltButton',
      selector: 'volt-button',
      inputs: [
        { name: 'variant', type: "ButtonVariants['variant']", default: "'solid'" },
        { name: 'size', type: "ButtonVariants['size']", default: "'md'" },
        { name: 'type', type: "'button' | 'submit' | 'reset'", default: "'button'" },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'class', type: 'string', default: "''" },
        { name: 'customClass', type: 'string', default: "''" },
      ],
      outputs: [],
    },
  ],
  variants: [
    {
      name: 'variant',
      options: ['solid', 'destructive', 'outline', 'ghost', 'link'],
      default: 'solid',
    },
    { name: 'size', options: ['sm', 'md', 'lg', 'icon'], default: 'md' },
  ],
};

export const CHECKBOX_API: ComponentApi = {
  directives: [
    {
      className: 'VoltCheckbox',
      selector: 'volt-checkbox',
      inputs: [
        { name: 'id', type: 'string', default: '`volt-checkbox-${++nextCheckboxId}`' },
        { name: 'checked', type: 'boolean', default: 'false' },
        { name: 'indeterminate', type: 'boolean', default: 'false' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'required', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [
        { name: 'checkedChange', type: 'boolean' },
        { name: 'indeterminateChange', type: 'boolean' },
      ],
    },
  ],
  variants: undefined,
};

export const COMBOBOX_API: ComponentApi = {
  directives: [
    {
      className: 'VoltComboboxButton',
      selector: 'volt-combobox-button',
      inputs: [
        { name: 'id', type: 'string', default: '`volt-combobox-button-${++nextComboboxButtonId}`' },
      ],
      outputs: [],
    },
    {
      className: 'VoltComboboxDropdown',
      selector: 'volt-combobox-dropdown',
      inputs: [
        {
          name: 'id',
          type: 'string',
          default: '`volt-combobox-dropdown-${++nextComboboxDropdownId}`',
        },
      ],
      outputs: [],
    },
    {
      className: 'VoltComboboxInput',
      selector: 'input[voltComboboxInput]',
      inputs: [{ name: 'id', type: 'unknown' }],
      outputs: [],
    },
    {
      className: 'VoltComboboxOption',
      selector: 'volt-combobox-option',
      inputs: [
        { name: 'value', type: 'unknown', required: true },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'index', type: 'number | undefined' },
      ],
      outputs: [{ name: 'activated', type: 'void' }],
    },
    {
      className: 'VoltCombobox',
      selector: 'volt-combobox',
      inputs: [
        { name: 'id', type: 'string', default: '`volt-combobox-${++nextComboboxId}`' },
        { name: 'label', type: 'string' },
        { name: 'value', type: 'unknown' },
        { name: 'multiple', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'allowDeselect', type: 'boolean', default: 'true', transform: 'booleanAttribute' },
        { name: 'compareWith', type: '(a: unknown, b: unknown) => boolean', default: 'Object.is' },
        { name: 'dropdownPlacement', type: 'NgpComboboxPlacement', default: "'bottom'" },
        { name: 'container', type: 'string | HTMLElement | null', default: "'body'" },
        { name: 'flip', type: 'NgpFlipInput', default: 'true' },
        {
          name: 'scrollToOption',
          type: '((index: number) => void) | undefined',
          default: 'undefined',
        },
        { name: 'allOptions', type: 'unknown[] | undefined', default: 'undefined' },
        { name: 'items', type: 'unknown[]', default: '[]' },
        { name: 'placeholder', type: 'string', default: "'Select...'" },
        {
          name: 'itemLabel',
          type: '(item: unknown) => string',
          default: "item =>\n    typeof item === 'string' ? item : String(item)",
        },
        {
          name: 'trackByFn',
          type: '(index: number, item: unknown) => unknown',
          default: '(_i, item) => item',
        },
      ],
      outputs: [{ name: 'valueChange', type: 'unknown' }],
    },
  ],
  variants: undefined,
};

export const DATE_PICKER_API: ComponentApi = {
  directives: [
    {
      className: 'VoltDatePickerLabel',
      selector: 'volt-date-picker-label',
      inputs: [
        { name: 'id', type: 'string' },
        { name: 'ariaLive', type: 'string', default: "'polite'" },
        { name: 'aria-live', type: 'unknown' },
      ],
      outputs: [],
    },
    {
      className: 'VoltDatePicker',
      selector: 'volt-date-picker',
      inputs: [
        { name: 'min', type: 'Date' },
        { name: 'max', type: 'Date' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'dateDisabled', type: '(date: Date) => boolean', default: '() => false' },
        { name: 'firstDayOfWeek', type: 'VoltDatePickerFirstDayOfWeek', default: '7' },
        { name: 'date', type: 'Date | undefined' },
        { name: 'focusedDate', type: 'Date', default: 'new Date()' },
        { name: 'isDisabled', type: 'unknown' },
      ],
      outputs: [
        { name: 'dateChange', type: 'Date | undefined' },
        { name: 'focusedDateChange', type: 'Date' },
      ],
    },
    {
      className: 'VoltDateRangePicker',
      selector: 'volt-date-range-picker',
      inputs: [
        { name: 'min', type: 'Date' },
        { name: 'max', type: 'Date' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'dateDisabled', type: '(date: Date) => boolean', default: '() => false' },
        { name: 'firstDayOfWeek', type: 'VoltDatePickerFirstDayOfWeek', default: '7' },
        { name: 'startDate', type: 'Date | undefined' },
        { name: 'endDate', type: 'Date | undefined' },
        { name: 'focusedDate', type: 'Date', default: 'new Date()' },
      ],
      outputs: [
        { name: 'startDateChange', type: 'Date | undefined' },
        { name: 'endDateChange', type: 'Date | undefined' },
        { name: 'focusedDateChange', type: 'Date' },
      ],
    },
  ],
  variants: undefined,
};

export const DIALOG_API: ComponentApi = {
  directives: [
    {
      className: 'VoltDialogContent',
      selector: '[voltDialogContent]',
      inputs: [
        { name: 'class', type: 'string', default: "''" },
        { name: 'role', type: 'unknown' },
        { name: 'modal', type: 'unknown' },
      ],
      outputs: [],
    },
    {
      className: 'VoltDialogOverlay',
      selector: '[voltDialogOverlay]',
      inputs: [{ name: 'closeOnClick', type: 'unknown' }],
      outputs: [],
    },
    {
      className: 'VoltDialog',
      selector: '[voltDialog]',
      inputs: [
        { name: 'voltDialog', type: 'unknown' },
        { name: 'closeOnEscape', type: 'unknown' },
      ],
      outputs: [{ name: 'closed', type: 'unknown' }],
    },
  ],
  variants: undefined,
};

export const DRAWER_API: ComponentApi = {
  directives: [
    {
      className: 'VoltDrawerContent',
      selector: '[voltDrawerContent]',
      inputs: [
        { name: 'side', type: 'DrawerSide', default: "'right'" },
        { name: 'class', type: 'string', default: "''" },
        { name: 'role', type: 'unknown' },
        { name: 'modal', type: 'unknown' },
      ],
      outputs: [],
    },
    {
      className: 'VoltDrawerOverlay',
      selector: '[voltDrawerOverlay]',
      inputs: [{ name: 'closeOnClick', type: 'unknown' }],
      outputs: [],
    },
    {
      className: 'VoltDrawer',
      selector: '[voltDrawer]',
      inputs: [{ name: 'voltDrawer', type: 'unknown' }],
      outputs: [{ name: 'closed', type: 'unknown' }],
    },
  ],
  variants: undefined,
};

export const DROPDOWN_MENU_API: ComponentApi = {
  directives: [
    {
      className: 'VoltDropdownMenuSubmenuTrigger',
      selector: 'volt-dropdown-menu-submenu-trigger',
      inputs: [
        { name: 'submenu', type: 'NgpOverlayContent<unknown> | undefined', default: 'undefined' },
        { name: 'placement', type: 'NgpMenuPlacement', default: "'right-start'" },
        { name: 'offset', type: 'number', default: '4' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
    {
      className: 'VoltDropdownMenuTrigger',
      selector: '[voltDropdownMenu]',
      inputs: [
        {
          name: 'voltDropdownMenu',
          type: 'NgpOverlayContent<unknown> | undefined',
          default: 'undefined',
        },
        { name: 'placement', type: 'NgpMenuPlacement', default: "'bottom-start'" },
        { name: 'offset', type: 'NgpOffset', default: '4' },
        { name: 'flip', type: 'NgpFlip', default: 'true' },
        { name: 'shift', type: 'NgpShift', default: 'true' },
        { name: 'container', type: 'HTMLElement | string | null', default: 'null' },
        {
          name: 'scrollBehavior',
          type: "'reposition' | 'block' | 'close'",
          default: "'reposition'",
        },
        { name: 'cooldown', type: 'number', default: '0' },
        { name: 'context', type: 'unknown', default: 'undefined' },
        {
          name: 'triggers',
          type: 'VoltMenuTriggerType[]',
          default: "['click', 'enter', 'arrowkey']",
        },
        { name: 'showDelay', type: 'number', default: '0' },
        { name: 'hideDelay', type: 'number', default: '0' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
  ],
  variants: undefined,
};

export const FILE_UPLOAD_API: ComponentApi = {
  directives: [
    {
      className: 'VoltFileDropzone',
      selector: 'volt-file-dropzone',
      inputs: [
        { name: 'fileTypes', type: 'string | string[]' },
        { name: 'multiple', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'directory', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [
        { name: 'selected', type: 'FileList | null' },
        { name: 'rejected', type: 'void' },
        { name: 'dragOver', type: 'boolean' },
      ],
    },
    {
      className: 'VoltFileUpload',
      selector: '[voltFileUpload]',
      inputs: [
        { name: 'fileTypes', type: 'string | string[]' },
        { name: 'multiple', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'directory', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'dragDrop', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [
        { name: 'selected', type: 'FileList | null' },
        { name: 'canceled', type: 'void' },
        { name: 'rejected', type: 'void' },
        { name: 'dragOver', type: 'boolean' },
      ],
    },
  ],
  variants: undefined,
};

export const FORM_FIELD_API: ComponentApi = {
  directives: [
    {
      className: 'VoltLabel',
      selector: 'volt-label',
      inputs: [
        { name: 'error', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'htmlFor', type: 'string', default: "''" },
      ],
      outputs: [],
    },
  ],
  variants: undefined,
};

export const INPUT_API: ComponentApi = {
  directives: [
    {
      className: 'VoltInput',
      selector: 'volt-input',
      inputs: [
        { name: 'id', type: 'string', default: "''" },
        { name: 'type', type: 'string', default: "'text'" },
        { name: 'name', type: 'string', default: "''" },
        { name: 'placeholder', type: 'string', default: "''" },
        { name: 'autocomplete', type: 'string', default: "''" },
        { name: 'ariaLabel', type: 'string', default: "''" },
        { name: 'value', type: 'string', default: "''" },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'readonly', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'required', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [{ name: 'valueChange', type: 'string' }],
    },
  ],
  variants: undefined,
};

export const INPUT_OTP_API: ComponentApi = {
  directives: [
    {
      className: 'VoltInputOtp',
      selector: 'volt-input-otp',
      inputs: [
        { name: 'value', type: 'string', default: "''" },
        { name: 'length', type: 'number', default: '6', transform: 'numberAttribute' },
        { name: 'pattern', type: 'string', default: "'[0-9]'" },
        {
          name: 'inputMode',
          type: "'numeric' | 'text' | 'decimal' | 'tel' | 'search' | 'email' | 'url'",
          default: "'numeric'",
        },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'placeholder', type: 'string', default: "'○'" },
        { name: 'isDisabled', type: 'unknown' },
      ],
      outputs: [
        { name: 'valueChange', type: 'string' },
        { name: 'complete', type: 'unknown' },
      ],
    },
  ],
  variants: undefined,
};

export const LISTBOX_API: ComponentApi = {
  directives: [
    {
      className: 'VoltListboxHeader',
      selector: 'volt-listbox-header',
      inputs: [{ name: 'id', type: 'string' }],
      outputs: [],
    },
    {
      className: 'VoltListboxOption',
      selector: 'volt-listbox-option',
      inputs: [
        { name: 'id', type: 'string' },
        { name: 'value', type: 'T', required: true },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'inset', type: "ListboxOptionVariants['inset']", default: 'false' },
      ],
      outputs: [],
    },
    {
      className: 'VoltListbox',
      selector: 'volt-listbox',
      inputs: [
        { name: 'id', type: 'string' },
        { name: 'mode', type: 'NgpSelectionMode', default: "'single'" },
        { name: 'value', type: 'T[]', default: '[]' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'compareWith', type: '(a: T, b: T) => boolean', default: '(a, b) => a === b' },
        { name: 'isDisabled', type: 'unknown' },
      ],
      outputs: [{ name: 'valueChange', type: 'T[]' }],
    },
  ],
  variants: [{ name: 'inset', options: ['true', 'false'], default: undefined }],
};

export const METER_API: ComponentApi = {
  directives: [
    {
      className: 'VoltMeter',
      selector: 'volt-meter',
      inputs: [
        { name: 'value', type: 'number', default: '0', transform: 'numberAttribute' },
        { name: 'min', type: 'number', default: '0', transform: 'numberAttribute' },
        { name: 'max', type: 'number', default: '100', transform: 'numberAttribute' },
        { name: 'valueLabel', type: '(value: number, max: number) => string' },
      ],
      outputs: [],
    },
  ],
  variants: undefined,
};

export const NAVIGATION_MENU_API: ComponentApi = {
  directives: [
    {
      className: 'VoltNavigationMenuContentItem',
      selector: 'volt-navigation-menu-content-item',
      inputs: [
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
    {
      className: 'VoltNavigationMenuContent',
      selector: 'volt-navigation-menu-content',
      inputs: [
        { name: 'orientation', type: "'vertical' | 'horizontal'", default: "'vertical'" },
        { name: 'wrap', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
    {
      className: 'VoltNavigationMenuItem',
      selector: 'volt-navigation-menu-item',
      inputs: [{ name: 'value', type: 'string' }],
      outputs: [],
    },
    {
      className: 'VoltNavigationMenuLink',
      selector: 'a[volt-navigation-menu-link]',
      inputs: [
        { name: 'active', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
    {
      className: 'VoltNavigationMenuList',
      selector: 'volt-navigation-menu-list',
      inputs: [{ name: 'wrap', type: 'boolean', default: 'false', transform: 'booleanAttribute' }],
      outputs: [],
    },
    {
      className: 'VoltNavigationMenuTrigger',
      selector: 'volt-navigation-menu-trigger',
      inputs: [
        { name: 'content', type: 'TemplateRef<unknown>', required: true },
        { name: 'placement', type: 'NavigationMenuPlacement', default: "'bottom-start'" },
        { name: 'offset', type: 'number', default: '4' },
        { name: 'flip', type: 'boolean', default: 'true', transform: 'booleanAttribute' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'cooldown', type: 'number', default: '300' },
      ],
      outputs: [],
    },
    {
      className: 'VoltNavigationMenu',
      selector: 'volt-navigation-menu',
      inputs: [
        { name: 'orientation', type: "'horizontal' | 'vertical'", default: "'horizontal'" },
        { name: 'showDelay', type: 'number', default: '200' },
        { name: 'hideDelay', type: 'number', default: '150' },
        { name: 'value', type: 'string | null', default: 'null' },
      ],
      outputs: [{ name: 'valueChange', type: 'string | null' }],
    },
  ],
  variants: undefined,
};

export const PAGINATION_API: ComponentApi = {
  directives: [
    {
      className: 'VoltPaginationButton',
      selector: 'volt-pagination-button',
      inputs: [
        { name: 'page', type: 'number', default: '{ transform: numberAttribute }', required: true },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'variant', type: "PaginationButtonVariants['variant']", default: "'default'" },
      ],
      outputs: [],
    },
    {
      className: 'VoltPaginationFirst',
      selector: 'volt-pagination-first',
      inputs: [
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
    {
      className: 'VoltPaginationLast',
      selector: 'volt-pagination-last',
      inputs: [
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
    {
      className: 'VoltPaginationNext',
      selector: 'volt-pagination-next',
      inputs: [
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
    {
      className: 'VoltPaginationPrevious',
      selector: 'volt-pagination-previous',
      inputs: [
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
    {
      className: 'VoltPagination',
      selector: 'volt-pagination',
      inputs: [
        { name: 'page', type: 'number', default: '1' },
        { name: 'pageCount', type: 'number', default: '0', transform: 'numberAttribute' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [{ name: 'pageChange', type: 'number' }],
    },
  ],
  variants: [
    {
      name: 'variant',
      options: ['default', 'hover', 'hover', 'outline', 'hover', 'hover'],
      default: 'default',
    },
  ],
};

export const POPOVER_API: ComponentApi = {
  directives: [
    {
      className: 'VoltPopoverArrow',
      selector: 'volt-popover-arrow',
      inputs: [
        { name: 'padding', type: 'number | undefined', default: '4' },
        { name: 'hidden', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
    {
      className: 'VoltPopoverTrigger',
      selector: '[voltPopover]',
      inputs: [
        {
          name: 'voltPopover',
          type: 'NgpOverlayContent<unknown> | undefined',
          default: 'undefined',
        },
        { name: 'placement', type: 'NgpPopoverPlacement', default: "'bottom'" },
        { name: 'offset', type: 'NgpOffset', default: '8' },
        { name: 'showDelay', type: 'number', default: '0' },
        { name: 'hideDelay', type: 'number', default: '0' },
        { name: 'flip', type: 'NgpFlip', default: 'true' },
        { name: 'shift', type: 'NgpShift', default: 'true' },
        { name: 'container', type: 'HTMLElement | string | null', default: 'null' },
        {
          name: 'scrollBehavior',
          type: "'reposition' | 'block' | 'close'",
          default: "'reposition'",
        },
        { name: 'context', type: 'unknown', default: 'undefined' },
        { name: 'anchor', type: 'HTMLElement | null', default: 'null' },
        { name: 'trackPosition', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'cooldown', type: 'number', default: '0' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        {
          name: 'closeOnOutsideClick',
          type: 'boolean',
          default: 'true',
          transform: 'booleanAttribute',
        },
        { name: 'closeOnEscape', type: 'boolean', default: 'true', transform: 'booleanAttribute' },
      ],
      outputs: [{ name: 'openChange', type: 'boolean' }],
    },
  ],
  variants: undefined,
};

export const PROGRESS_API: ComponentApi = {
  directives: [
    {
      className: 'VoltProgress',
      selector: 'volt-progress',
      inputs: [
        { name: 'value', type: 'number | null', default: 'null', transform: 'numberAttribute' },
        { name: 'min', type: 'number', default: '0', transform: 'numberAttribute' },
        { name: 'max', type: 'number', default: '100', transform: 'numberAttribute' },
      ],
      outputs: [],
    },
  ],
  variants: undefined,
};

export const RADIO_API: ComponentApi = {
  directives: [
    {
      className: 'VoltRadioGroup',
      selector: 'volt-radio-group',
      inputs: [
        { name: 'id', type: 'string' },
        { name: 'orientation', type: 'NgpOrientation', default: "'vertical'" },
        { name: 'value', type: 'string | null', default: 'null' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        {
          name: 'compareWith',
          type: '(a: string | null, b: string | null) => boolean',
          default: 'Object.is',
        },
      ],
      outputs: [{ name: 'valueChange', type: 'string | null' }],
    },
    {
      className: 'VoltRadioItem',
      selector: 'volt-radio-item',
      inputs: [
        { name: 'value', type: 'string', required: true },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
  ],
  variants: undefined,
};

export const RESIZABLE_API: ComponentApi = {
  directives: [
    {
      className: 'VoltResizableHandle',
      selector: 'volt-resizable-handle',
      inputs: [{ name: 'orientation', type: "'horizontal' | 'vertical'", default: "'horizontal'" }],
      outputs: [{ name: 'resizing', type: 'boolean' }],
    },
    {
      className: 'VoltResizablePanel',
      selector: 'volt-resizable-panel',
      inputs: [{ name: 'class', type: 'string', default: "''" }],
      outputs: [],
    },
    {
      className: 'VoltResizable',
      selector: 'volt-resizable',
      inputs: [
        { name: 'orientation', type: "'horizontal' | 'vertical'", default: "'horizontal'" },
        { name: 'class', type: 'string', default: "''" },
      ],
      outputs: [],
    },
  ],
  variants: undefined,
};

export const SELECT_API: ComponentApi = {
  directives: [
    {
      className: 'VoltNativeSelect',
      selector: 'volt-native-select',
      inputs: [
        { name: 'id', type: 'string', default: "''" },
        { name: 'name', type: 'string', default: "''" },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
    {
      className: 'VoltSelectItem',
      selector: 'volt-select-item',
      inputs: [
        { name: 'value', type: 'unknown', default: 'undefined' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
    {
      className: 'VoltSelect',
      selector: 'volt-select',
      inputs: [
        { name: 'placeholder', type: 'string', default: "'Select an option'" },
        { name: 'ariaLabel', type: 'string', default: "''" },
        { name: 'value', type: 'unknown', default: 'undefined' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'multiple', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [{ name: 'valueChange', type: 'unknown' }],
    },
  ],
  variants: undefined,
};

export const SEPARATOR_API: ComponentApi = {
  directives: [
    {
      className: 'VoltSeparator',
      selector: 'volt-separator',
      inputs: [{ name: 'orientation', type: "'horizontal' | 'vertical'", default: "'horizontal'" }],
      outputs: [],
    },
  ],
  variants: undefined,
};

export const SKELETON_API: ComponentApi = {
  directives: [
    {
      className: 'VoltSkeleton',
      selector: 'volt-skeleton',
      inputs: [
        { name: 'variant', type: "SkeletonVariants['variant']", default: "'rectangle'" },
        { name: 'class', type: 'string', default: "''" },
        { name: 'width', type: 'string', default: "'100%'" },
        { name: 'height', type: 'string', default: "'1rem'" },
      ],
      outputs: [],
    },
  ],
  variants: [{ name: 'variant', options: ['circle', 'rectangle', 'text'], default: 'rectangle' }],
};

export const SLIDER_API: ComponentApi = {
  directives: [
    {
      className: 'VoltSlider',
      selector: 'volt-slider',
      inputs: [
        { name: 'id', type: 'string' },
        { name: 'value', type: 'number', default: '0', transform: 'numberAttribute' },
        { name: 'min', type: 'number', default: '0', transform: 'numberAttribute' },
        { name: 'max', type: 'number', default: '100', transform: 'numberAttribute' },
        { name: 'step', type: 'number', default: '1', transform: 'numberAttribute' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'orientation', type: 'NgpOrientation', default: "'horizontal'" },
        { name: 'ariaLabel', type: 'string' },
      ],
      outputs: [{ name: 'valueChange', type: 'number' }],
    },
  ],
  variants: undefined,
};

export const SWITCH_API: ComponentApi = {
  directives: [
    {
      className: 'VoltSwitch',
      selector: 'volt-switch',
      inputs: [
        { name: 'id', type: 'string', default: '`volt-switch-${++nextSwitchId}`' },
        { name: 'ariaLabel', type: 'string', default: "''" },
        { name: 'checked', type: 'boolean', default: 'false' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [{ name: 'checkedChange', type: 'boolean' }],
    },
  ],
  variants: undefined,
};

export const TABLE_API: ComponentApi = {
  directives: [
    {
      className: 'VoltTableBody',
      selector: 'volt-table-body',
      inputs: [{ name: 'class', type: 'string', default: "''" }],
      outputs: [],
    },
    {
      className: 'VoltTableCaption',
      selector: 'volt-table-caption',
      inputs: [{ name: 'class', type: 'string', default: "''" }],
      outputs: [],
    },
    {
      className: 'VoltTableCell',
      selector: 'volt-table-cell',
      inputs: [{ name: 'class', type: 'string', default: "''" }],
      outputs: [],
    },
    {
      className: 'VoltTableFooter',
      selector: 'volt-table-footer',
      inputs: [{ name: 'class', type: 'string', default: "''" }],
      outputs: [],
    },
    {
      className: 'VoltTableHead',
      selector: 'volt-table-head',
      inputs: [{ name: 'class', type: 'string', default: "''" }],
      outputs: [],
    },
    {
      className: 'VoltTableHeader',
      selector: 'volt-table-header',
      inputs: [{ name: 'class', type: 'string', default: "''" }],
      outputs: [],
    },
    {
      className: 'VoltTableRow',
      selector: 'volt-table-row',
      inputs: [{ name: 'class', type: 'string', default: "''" }],
      outputs: [],
    },
    {
      className: 'VoltTable',
      selector: 'volt-table',
      inputs: [{ name: 'class', type: 'string', default: "''" }],
      outputs: [],
    },
  ],
  variants: undefined,
};

export const TABS_API: ComponentApi = {
  directives: [
    {
      className: 'VoltTabsContent',
      selector: 'volt-tabs-content',
      inputs: [{ name: 'value', type: 'string', required: true }],
      outputs: [],
    },
    {
      className: 'VoltTabsTrigger',
      selector: 'volt-tabs-trigger',
      inputs: [{ name: 'value', type: 'string', required: true }],
      outputs: [],
    },
    {
      className: 'VoltTabs',
      selector: 'volt-tabs',
      inputs: [
        { name: 'value', type: 'string | undefined', default: 'undefined' },
        { name: 'orientation', type: "'horizontal' | 'vertical'", default: "'horizontal'" },
        {
          name: 'activateOnFocus',
          type: 'boolean',
          default: 'true',
          transform: 'booleanAttribute',
        },
      ],
      outputs: [{ name: 'valueChange', type: 'string | undefined' }],
    },
  ],
  variants: undefined,
};

export const TEXTAREA_API: ComponentApi = {
  directives: [
    {
      className: 'VoltTextarea',
      selector: 'volt-textarea',
      inputs: [
        { name: 'id', type: 'string', default: "''" },
        { name: 'name', type: 'string', default: "''" },
        { name: 'placeholder', type: 'string', default: "''" },
        { name: 'variant', type: "TextareaVariants['variant']", default: "'default'" },
        { name: 'size', type: "TextareaVariants['size']", default: "'md'" },
        { name: 'state', type: "TextareaVariants['state']", default: "'default'" },
        {
          name: 'resize',
          type: "'none' | 'vertical' | 'horizontal' | 'both'",
          default: "'vertical'",
        },
        { name: 'rows', type: 'number', default: '3' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'readonly', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'required', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'value', type: 'string', default: "''" },
      ],
      outputs: [{ name: 'valueChange', type: 'string' }],
    },
  ],
  variants: [
    {
      name: 'variant',
      options: [
        'default',
        'focus-visible',
        'filled',
        'focus-visible',
        'focus-visible',
        'ghost',
        'focus-visible',
        'focus-visible',
      ],
      default: 'default',
    },
    { name: 'size', options: ['sm', 'md', 'lg'], default: 'md' },
    {
      name: 'state',
      options: ['default', 'error', 'focus-visible', 'placeholder'],
      default: 'default',
    },
  ],
};

export const TOAST_API: ComponentApi = {
  directives: [
    {
      className: 'VoltToastClose',
      selector: 'volt-toast-close',
      inputs: [],
      outputs: [{ name: 'closeChange', type: 'void' }],
    },
    {
      className: 'VoltToast',
      selector: 'volt-toast',
      inputs: [{ name: 'variant', type: "ToastVariants['variant']", default: "'default'" }],
      outputs: [],
    },
  ],
  variants: [
    {
      name: 'variant',
      options: ['default', 'success', 'error', 'warning', 'info'],
      default: 'default',
    },
  ],
};

export const TOGGLE_API: ComponentApi = {
  directives: [
    {
      className: 'VoltToggle',
      selector: 'volt-toggle',
      inputs: [
        { name: 'variant', type: "ToggleVariants['variant']", default: "'default'" },
        { name: 'size', type: "ToggleVariants['size']", default: "'md'" },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'pressed', type: 'boolean', default: 'false' },
      ],
      outputs: [{ name: 'pressedChange', type: 'boolean' }],
    },
  ],
  variants: [
    {
      name: 'variant',
      options: [
        'default',
        'outline',
        'hover',
        'hover',
        'ghost',
        'hover',
        'hover',
        'solid',
        'hover',
      ],
      default: 'default',
    },
    { name: 'size', options: ['sm', 'md', 'lg', 'icon'], default: 'md' },
  ],
};

export const TOGGLE_GROUP_API: ComponentApi = {
  directives: [
    {
      className: 'VoltToggleGroupItem',
      selector: 'volt-toggle-group-item',
      inputs: [
        { name: 'value', type: 'string', required: true },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'variant', type: "ToggleGroupItemVariants['variant']", default: "'default'" },
        { name: 'size', type: "ToggleGroupItemVariants['size']", default: "'md'" },
      ],
      outputs: [],
    },
    {
      className: 'VoltToggleGroup',
      selector: 'volt-toggle-group',
      inputs: [
        { name: 'value', type: 'string[]', default: '[]' },
        { name: 'type', type: "'single' | 'multiple'", default: "'single'" },
        { name: 'orientation', type: "'horizontal' | 'vertical'", default: "'horizontal'" },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        {
          name: 'allowDeselection',
          type: 'boolean',
          default: 'true',
          transform: 'booleanAttribute',
        },
      ],
      outputs: [{ name: 'valueChange', type: 'string[]' }],
    },
  ],
  variants: [
    {
      name: 'variant',
      options: ['default', 'hover', 'hover', 'outline', 'hover', 'hover'],
      default: 'default',
    },
    { name: 'size', options: ['sm', 'md', 'lg'], default: 'md' },
  ],
};

export const TOOLBAR_API: ComponentApi = {
  directives: [
    {
      className: 'VoltToolbar',
      selector: 'volt-toolbar',
      inputs: [{ name: 'orientation', type: 'NgpOrientation', default: "'horizontal'" }],
      outputs: [],
    },
  ],
  variants: undefined,
};

export const TOOLTIP_API: ComponentApi = {
  directives: [
    {
      className: 'VoltTooltipArrow',
      selector: 'volt-tooltip-arrow',
      inputs: [
        { name: 'padding', type: 'number | undefined', default: '4' },
        { name: 'hidden', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
    {
      className: 'VoltTooltip',
      selector: '[voltTooltip]',
      inputs: [
        {
          name: 'voltTooltip',
          type: 'NgpOverlayContent<unknown> | string | null',
          default: 'null',
        },
        { name: 'placement', type: 'NgpTooltipPlacement', default: "'top'" },
        { name: 'offset', type: 'NgpOffset', default: '8' },
        { name: 'delay', type: 'number', default: '300' },
        { name: 'closeDelay', type: 'number', default: '100' },
        { name: 'flip', type: 'NgpFlip', default: 'true' },
        { name: 'shift', type: 'NgpShift', default: 'true' },
        { name: 'container', type: 'HTMLElement | string | null', default: 'null' },
        {
          name: 'showOnOverflow',
          type: 'boolean',
          default: 'false',
          transform: 'booleanAttribute',
        },
        { name: 'context', type: 'unknown', default: 'undefined' },
        { name: 'disabled', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        {
          name: 'useTextContent',
          type: 'boolean',
          default: 'false',
          transform: 'booleanAttribute',
        },
        { name: 'trackPosition', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
        { name: 'position', type: 'NgpPosition | null', default: 'null' },
        { name: 'scrollBehavior', type: "'reposition' | 'close'", default: "'reposition'" },
        { name: 'cooldown', type: 'number', default: '300' },
      ],
      outputs: [],
    },
  ],
  variants: undefined,
};

export const SIDEBAR_API: ComponentApi = {
  directives: [
    {
      className: 'VoltSidebar',
      selector: 'volt-sidebar',
      inputs: [
        { name: 'label', type: 'string' },
        { name: 'routerLink', type: 'string', required: true },
        { name: 'exact', type: 'boolean', default: 'false', transform: 'booleanAttribute' },
      ],
      outputs: [],
    },
  ],
  variants: undefined,
};
